---
    name: Create and push Docker image

    on:
      push: 
        branches:
          - main
    
    jobs:
        docker:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout code
                  uses: actions/checkout@v2
                - name: Setting up docker buildx
                  uses: docker/setup-buildx-action@v3
                - name: Login to DockerHub
                  uses: docker/login-action@v3
                  with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                - name: Build and push
                  uses: docker/build-push-action@v6
                  with:
                    push: true
                    tags: |
                        ${{ secrets.DOCKER_USERNAME }}/devops-flask:latest
                        ${{ secrets.DOCKER_USERNAME }}/devops-flask:${{ github.sha }}
                    cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/devops-flask:buildcache
                    cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/devops-flask:buildcache,mode=max